### ISSUE TITLE
Is there any way to only get the prestrafe part of this plugin?

### ISSUE THREAD

**Issue by Icuu** [danzayau/MovementTweaker#2]
When I bhop, prestrafe is either locked to 240-260 (depending on weapon) but since your plugin unlocks it to 276 thats great. But, thats the only part of the plugin. The perfect bhop kills my speed. Any way of only getting the prestrafe part?

**Comment by danzayau** [comment]
After running the plugin, it should generate csgo/cfg/sourcemod/MovementTweaker.cfg. These are several convars you can hopefully use to control the features of the plugin. Tell me if you aren't able to get what you desire.

**Note:** You should delete this when updating the plugin as I have added a couple of new convars.

**Comment by Icuu** [comment]
Thank you if work perfectly!
